#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  printf 'Source this file rather than executing it:\n  source %q\n' "$0" >&2
  exit 1
fi

SCHWARZMAN_ACTIVATE_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
SCHWARZMAN_DEV_ROOT="$(cd -- "$SCHWARZMAN_ACTIVATE_SCRIPT_DIR/.." && pwd -P)"

source "$SCHWARZMAN_DEV_ROOT/versions.env"
source "$SCHWARZMAN_ACTIVATE_SCRIPT_DIR/_common.bash"

schwarzman_dev_detect_host || return 1

SCHWARZMAN_DEV_NODE_DIST_NAME="node-v${SCHWARZMAN_ATRIUM_NODE_VERSION}-${SCHWARZMAN_DEV_OS}-${SCHWARZMAN_DEV_ARCH}"
SCHWARZMAN_DEV_NODE_HOME="$SCHWARZMAN_ACTIVATE_SCRIPT_DIR/installed/$SCHWARZMAN_DEV_NODE_DIST_NAME"

if [[ "$SCHWARZMAN_DEV_OS" == "win" ]]; then
  SCHWARZMAN_DEV_NODE_BIN_DIR="$SCHWARZMAN_DEV_NODE_HOME"
  SCHWARZMAN_DEV_NODE_EXECUTABLE="$SCHWARZMAN_DEV_NODE_HOME/node.exe"
else
  SCHWARZMAN_DEV_NODE_BIN_DIR="$SCHWARZMAN_DEV_NODE_HOME/bin"
  SCHWARZMAN_DEV_NODE_EXECUTABLE="$SCHWARZMAN_DEV_NODE_BIN_DIR/node"
fi

if [[ ! -x "$SCHWARZMAN_DEV_NODE_EXECUTABLE" ]]; then
  printf 'Node.js is not installed in this dev submodule. Run:\n  %s/INSTALL-DEV-TOOLS-ALL.sh\n' \
    "$SCHWARZMAN_DEV_ROOT" >&2
  return 1
fi

case ":$PATH:" in
  *":$SCHWARZMAN_DEV_NODE_BIN_DIR:"*) ;;
  *) export PATH="$SCHWARZMAN_DEV_NODE_BIN_DIR:$PATH" ;;
esac

SCHWARZMAN_DEV_COREPACK_HOME="$SCHWARZMAN_ACTIVATE_SCRIPT_DIR/installed/corepack"
export SCHWARZMAN_DEV_ROOT
export SCHWARZMAN_DEV_NODE_HOME
export SCHWARZMAN_DEV_NODE_BIN_DIR
export COREPACK_HOME="$SCHWARZMAN_DEV_COREPACK_HOME"
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0

hash -r
unset SCHWARZMAN_ACTIVATE_SCRIPT_DIR SCHWARZMAN_DEV_NODE_DIST_NAME
unset SCHWARZMAN_DEV_NODE_EXECUTABLE SCHWARZMAN_DEV_COREPACK_HOME
